CLAUDE_COPPER = "#DA7756"
CLAUDE_CREAM = "#EEECE2"
CLAUDE_INK = "#3D3929"
CLAUDE_DARK = "#141413"
CLAUDE_BONE = "#F0EEE6"
CLAUDE_MID_GRAY = "#B0AEA5"
CLAUDE_LIGHT_GRAY = "#E8E6DC"
CLAUDE_BLUE = "#6A9BCC"
CLAUDE_GREEN = "#788C5D"

BG = CLAUDE_DARK
FG = CLAUDE_BONE
ACCENT = CLAUDE_COPPER
MUTED = CLAUDE_MID_GRAY
ACCENT_2 = CLAUDE_BLUE
ACCENT_3 = CLAUDE_GREEN
